export const UserAction = {
  LOGOUT: 'LOGOUT',

  GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
  GET_ACCESS_TOKEN_SUCCESS: 'GET_ACCESS_TOKEN_SUCCESS',
  GET_ACCESS_TOKEN_FAILURE: 'GET_ACCESS_TOKEN_FAILURE',

  ADD_TO_SLACK: 'ADD_TO_SLACK',
  ADD_TO_SLACK_SUCCESS: 'ADD_TO_SLACK_SUCCESS',
  ADD_TO_SLACK_FAILURE: 'ADD_TO_SLACK_FAILURE',

  CONNECT_SLACK: 'CONNECT_SLACK',
  CONNECT_SLACK_SUCCESS: 'CONNECT_SLACK_SUCCESS',
  CONNECT_SLACK_FAILURE: 'CONNECT_SLACK_FAILURE',

  EMAIL_LOGIN: 'EMAIL_LOGIN',
  EMAIL_LOGIN_SUCCESS: 'EMAIL_LOGIN_SUCCESS',
  EMAIL_LOGIN_FAILURE: 'EMAIL_LOGIN_FAILURE',

  EMAIL_SIGNUP: 'EMAIL_SIGNUP',
  EMAIL_SIGNUP_SUCCESS: 'EMAIL_SIGNUP_SUCCESS',
  EMAIL_SIGNUP_FAILURE: 'EMAIL_SIGNUP_FAILURE',

  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  GET_INFO_FAILURE: 'GET_INFO_FAILURE',

  GET_REFERRALS: 'GET_REFERRALS',
  GET_TRANSACTION: 'GET_TRANSACTION',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILURE: 'GET_TRANSACTION_FAILURE',

  GET_STATE: 'GET_STATE',
  GET_STATE_SUCCESS: 'GET_STATE_SUCCESS',
  GET_STATE_FAILURE: 'GET_STATE_FAILURE',

  UPDATE_STATE: 'UPDATE_STATE',

  GET_PROBLEMS: 'GET_PROBLEMS',
  GET_PROBLEMS_SUCCESS: 'GET_PROBLEMS_SUCCESS',

  UPDATE_INFO: 'UPDATE_INFO',
  UPDATE_INFO_SUCCESS: 'UPDATE_INFO_SUCCESS',
  UPDATE_INFO_FAILURE: 'UPDATE_INFO_FAILURE',

  UPDATE_OBFUSCATION: 'UPDATE_OBFUSCATION',
  UPDATE_OBFUSCATION_SUCCESS: 'UPDATE_OBFUSCATION_SUCCESS',
  UPDATE_OBFUSCATION_FAILURE: 'UPDATE_OBFUSCATION_FAILURE',

  UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
  UPDATE_PHONE_NUMBER_SUCCESS: 'UPDATE_PHONE_NUMBER_SUCCESS',
  UPDATE_PHONE_NUMBER_FAILURE: 'UPDATE_PHONE_NUMBER_FAILURE',

  GET_GOOGLE_CONTACTS: 'GET_GOOGLE_CONTACTS',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  CONNECT_FACEBOOK: 'CONNECT_FACEBOOK',
  CONNECT_FACEBOOK_SUCCESS: 'CONNECT_FACEBOOK_SUCCESS',

  CONNECT_GOOGLE: 'CONNECT_GOOGLE',
  CONNECT_GOOGLE_SUCCESS: 'CONNECT_GOOGLE_SUCCESS',

  CONNECT_LINKEDIN: 'CONNECT_LINKEDIN',
  CONNECT_LINKEDIN_SUCCESS: 'CONNECT_LINKEDIN_SUCCESS',

  RECOVER_PASSWORD: 'RECOVER_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  VERIFY_PASSWORD_RECOVERY_CODE: 'VERIFY_PASSWORD_RECOVERY_CODE',

  CONFIRM_REWARD: 'CONFIRM_REWARD',

  SEND_REFERRAL_EMAILS: 'SEND_REFERRAL_EMAILS',
  SUBSCRIBE_EMAIL: 'SUBSCRIBE_EMAIL',

  GET_BRAINTREE_CLIENT_TOKEN: 'GET_BRAINTREE_CLIENT_TOKEN',
  GET_BRAINTREE_CLIENT_TOKEN_SUCCESS: 'GET_BRAINTREE_CLIENT_TOKEN_SUCCESS',

  ADD_PAYMENT_METHOD: 'ADD_PAYMENT_METHOD',
  ADD_PAYMENT_METHOD_SUCCESS: 'ADD_PAYMENT_METHOD_SUCCESS',

  ADD_PAYMENT_METHOD_IN_LANDING: 'ADD_PAYMENT_METHOD_IN_LANDING',

  UPDATE_PAYMENT_METHODS: 'UPDATE_PAYMENT_METHODS',

  GET_CREDIT_PACKAGES: 'GET_CREDIT_PACKAGES',
  GET_CREDIT_PACKAGES_SUCCESS: 'GET_CREDIT_PACKAGES_SUCCESS',

  GET_CREDIT_PACKAGES_WHEN_FINISH_SESSION: 'GET_CREDIT_PACKAGES_WHEN_FINISH_SESSION',
  GET_CREDIT_PACKAGES_WHEN_FINISH_SESSION_SUCCESS: 'GET_CREDIT_PACKAGES_WHEN_FINISH_SESSION_SUCCESS',

  GET_ZOOM_PAYWALL_DATA: 'GET_ZOOM_PAYWALL_DATA',
  GET_ZOOM_PAYWALL_DATA_SUCCESS: 'GET_ZOOM_PAYWALL_DATA_SUCCESS',

  PURCHASE_CREDIT_PACKAGES: 'PURCHASE_CREDIT_PACKAGES',

  UPDATE_BALANCE: 'UPDATE_BALANCE',

  GET_UTM_OFFER_PACKAGE: 'GET_UTM_OFFER_PACKAGE',

  CHECK_EXISTED_EMAIL: 'CHECK_EXISTED_EMAIL',
  CHECK_EU: 'CHECK_EU',

  RESET_IDLE_TIMEOUT: 'RESET_IDLE_TIMEOUT',
};

export const PublicAction = {

};