export const UserAction = {
  LOGIN_GOOGLE: 'LOGIN_GOOGLE',
  LOGIN_GOOGLE_SUCCESS: 'LOGIN_GOOGLE_SUCCESS',
  LOGIN_GOOGLE_FAILURE: 'LOGIN_GOOGLE_FAILURE',

  LOGOUT: 'LOGOUT',

  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',

  GET_USER_BLOG: 'GET_USER_BLOG',
  GET_USER_BLOG_SUCCESS: 'GET_USER_BLOG_SUCCESS',
  GET_USER_BLOG_FAILURE: 'GET_USER_BLOG_FAILURE',

  DELETE_BLOG: 'DELETE_BLOG',
  DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
  DELETE_BLOG_FAILURE: 'DELETE_BLOG_FAILURE',
};

export const BlogAction = {
  GET_BLOG_BY_ID: 'GET_BLOG_BY_ID',
  GET_BLOG_BY_ID_SUCCESS: 'GET_BLOG_BY_ID_SUCCESS',
  GET_BLOG_BY_ID_FAILURE: 'GET_BLOG_BY_ID_FAILURE',

  LIKE_BLOG: 'LIKE_BLOG',
  LIKE_BLOG_SUCCESS: 'LIKE_BLOG_SUCCESS',
  LIKE_BLOG_FAILURE: 'LIKE_BLOG_FAILURE',
};

export const AppAction = {
  GET_ALL_BLOGS: 'GET_ALL_BLOGS',
  GET_ALL_BLOGS_SUCCESS: 'GET_ALL_BLOGS_SUCCESS',
  GET_ALL_BLOGS_FAILURE: 'GET_ALL_BLOGS_FAILURE',

  GET_TRENDING_BLOGS: 'GET_TRENDING_BLOGS',
  GET_TRENDING_BLOGS_SUCCESS: 'GET_TRENDING_BLOGS_SUCCESS',
  GET_TRENDING_BLOGS_FAILURE: 'GET_TRENDING_BLOGS_FAILURE',
};